In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [13]:
import joblib

scaler_upscaled = joblib.load(r'/content/drive/MyDrive/Diabetes/Diabetes_models/scaler_after_upscale.pkl')
vc = joblib.load(r'/content/drive/MyDrive/Diabetes/Diabetes_models/vc.pkl')
bbc_upscale = joblib.load(r'/content/drive/MyDrive/Diabetes/Diabetes_models/bbc_after_upscale.pkl')

['age', 'hypertension', 'heart_disease', 'bmi', 'HbA1c_level',
       'blood_glucose_level', 'gender_Female', 'gender_Male', 'gender_Other',
       'smoking_history_No Info', 'smoking_history_current',
       'smoking_history_ever', 'smoking_history_former',
       'smoking_history_never', 'smoking_history_not current']

[54.0,0,0,34.32,6.5,200,0,1,0,0,0,1,0,0,0]  = yes

[24.0,0,0,35.42,4.0,100,1,0,0,0,0,0,0,1,0] = no

In [8]:
import numpy as np
features = [24.0,0,0,35.42,4.0,100,1,0,0,0,0,0,0,1,0]
test = [np.array(features)]

In [9]:
vc.predict(scaler_upscaled.transform(test))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

In [10]:
scaler_upscaled.transform(test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.23161046, -0.4270291 , -0.31339312,  0.7985386 , -1.69087388,
        -1.11481121,  0.89081702, -0.89063944, -0.00991818, -0.61333338,
        -0.33688408, -0.22249606, -0.39552743,  1.30434135, -0.27872521]])

In [14]:
bbc_upscale.predict(scaler_upscaled.transform(test)) 

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

In [15]:
scaler_noupscaled = joblib.load(r'/content/drive/MyDrive/Diabetes/Diabetes_models/scaler_no_upscale.pkl')
bbc_noupscale = joblib.load(r'/content/drive/MyDrive/Diabetes/Diabetes_models/bbc_no_upscale.pkl')

In [16]:
bbc_noupscale.predict(scaler_noupscaled.transform(test)) 

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])